// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"UserCode/Article.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Articles/AddEditArticle.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Articles/ViewArticle.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/ArticleTypes/ViewArticleType.lsml.js\"></script>");
