//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_Inserting(global::LightSwitchApplication.Article entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_Inserted(global::LightSwitchApplication.Article entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_Updating(global::LightSwitchApplication.Article entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_Updated(global::LightSwitchApplication.Article entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_Deleting(global::LightSwitchApplication.Article entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_Deleted(global::LightSwitchApplication.Article entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_Validate(global::LightSwitchApplication.Article entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Articles_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Article, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_Inserting(global::LightSwitchApplication.ArticleType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_Inserted(global::LightSwitchApplication.ArticleType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_Updating(global::LightSwitchApplication.ArticleType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_Updated(global::LightSwitchApplication.ArticleType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_Deleting(global::LightSwitchApplication.ArticleType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_Deleted(global::LightSwitchApplication.ArticleType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_Validate(global::LightSwitchApplication.ArticleType entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleTypes_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ArticleType, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_Inserting(global::LightSwitchApplication.Author entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_Inserted(global::LightSwitchApplication.Author entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_Updating(global::LightSwitchApplication.Author entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_Updated(global::LightSwitchApplication.Author entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_Deleting(global::LightSwitchApplication.Author entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_Deleted(global::LightSwitchApplication.Author entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_Validate(global::LightSwitchApplication.Author entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Authors_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Author, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_Inserting(global::LightSwitchApplication.Result entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_Inserted(global::LightSwitchApplication.Result entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_Updating(global::LightSwitchApplication.Result entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_Updated(global::LightSwitchApplication.Result entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_Deleting(global::LightSwitchApplication.Result entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_Deleted(global::LightSwitchApplication.Result entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_Validate(global::LightSwitchApplication.Result entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Results_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Result, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_Inserting(global::LightSwitchApplication.StudyDesign entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_Inserted(global::LightSwitchApplication.StudyDesign entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_Updating(global::LightSwitchApplication.StudyDesign entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_Updated(global::LightSwitchApplication.StudyDesign entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_Deleting(global::LightSwitchApplication.StudyDesign entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_Deleted(global::LightSwitchApplication.StudyDesign entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_Validate(global::LightSwitchApplication.StudyDesign entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyDesigns_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StudyDesign, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_Inserting(global::LightSwitchApplication.StudyTarget entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_Inserted(global::LightSwitchApplication.StudyTarget entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_Updating(global::LightSwitchApplication.StudyTarget entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_Updated(global::LightSwitchApplication.StudyTarget entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_Deleting(global::LightSwitchApplication.StudyTarget entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_Deleted(global::LightSwitchApplication.StudyTarget entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_Validate(global::LightSwitchApplication.StudyTarget entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StudyTargets_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StudyTarget, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_Inserting(global::LightSwitchApplication.TargetType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_Inserted(global::LightSwitchApplication.TargetType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_Updating(global::LightSwitchApplication.TargetType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_Updated(global::LightSwitchApplication.TargetType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_Deleting(global::LightSwitchApplication.TargetType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_Deleted(global::LightSwitchApplication.TargetType entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_Validate(global::LightSwitchApplication.TargetType entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TargetTypes_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.TargetType, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Article>
                __ArticlesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Article>(
                    "Articles",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Articles_Filter);
            private static bool __Articles_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Articles_CanInsert(ref result);
                return result;
            }
            private static bool __Articles_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Articles_CanUpdate(ref result);
                return result;
            }
            private static bool __Articles_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Articles_CanDelete(ref result);
                return result;
            }
            private static bool __Articles_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Articles_CanRead(ref result);
                return result;
            }
            private static void __Articles_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Article e)
            {
                d.Articles_Inserting(e);
            }
            private static void __Articles_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Article e)
            {
                d.Articles_Inserted(e);
            }
            private static void __Articles_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Article e)
            {
                d.Articles_Updating(e);
            }
            private static void __Articles_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Article e)
            {
                d.Articles_Updated(e);
            }
            private static void __Articles_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Article e)
            {
                d.Articles_Deleting(e);
            }
            private static void __Articles_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Article e)
            {
                d.Articles_Deleted(e);
            }
            private static void __Articles_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Articles_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Article, bool>> __Articles_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Article, bool>> filter = null;
                d.Articles_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.ArticleType>
                __ArticleTypesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.ArticleType>(
                    "ArticleTypes",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ArticleTypes_Filter);
            private static bool __ArticleTypes_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ArticleTypes_CanInsert(ref result);
                return result;
            }
            private static bool __ArticleTypes_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ArticleTypes_CanUpdate(ref result);
                return result;
            }
            private static bool __ArticleTypes_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ArticleTypes_CanDelete(ref result);
                return result;
            }
            private static bool __ArticleTypes_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ArticleTypes_CanRead(ref result);
                return result;
            }
            private static void __ArticleTypes_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ArticleType e)
            {
                d.ArticleTypes_Inserting(e);
            }
            private static void __ArticleTypes_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ArticleType e)
            {
                d.ArticleTypes_Inserted(e);
            }
            private static void __ArticleTypes_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ArticleType e)
            {
                d.ArticleTypes_Updating(e);
            }
            private static void __ArticleTypes_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ArticleType e)
            {
                d.ArticleTypes_Updated(e);
            }
            private static void __ArticleTypes_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ArticleType e)
            {
                d.ArticleTypes_Deleting(e);
            }
            private static void __ArticleTypes_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ArticleType e)
            {
                d.ArticleTypes_Deleted(e);
            }
            private static void __ArticleTypes_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ArticleType e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.ArticleTypes_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ArticleType, bool>> __ArticleTypes_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ArticleType, bool>> filter = null;
                d.ArticleTypes_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Author>
                __AuthorsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Author>(
                    "Authors",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Authors_Filter);
            private static bool __Authors_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Authors_CanInsert(ref result);
                return result;
            }
            private static bool __Authors_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Authors_CanUpdate(ref result);
                return result;
            }
            private static bool __Authors_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Authors_CanDelete(ref result);
                return result;
            }
            private static bool __Authors_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Authors_CanRead(ref result);
                return result;
            }
            private static void __Authors_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Author e)
            {
                d.Authors_Inserting(e);
            }
            private static void __Authors_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Author e)
            {
                d.Authors_Inserted(e);
            }
            private static void __Authors_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Author e)
            {
                d.Authors_Updating(e);
            }
            private static void __Authors_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Author e)
            {
                d.Authors_Updated(e);
            }
            private static void __Authors_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Author e)
            {
                d.Authors_Deleting(e);
            }
            private static void __Authors_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Author e)
            {
                d.Authors_Deleted(e);
            }
            private static void __Authors_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Author e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Authors_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Author, bool>> __Authors_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Author, bool>> filter = null;
                d.Authors_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Result>
                __ResultsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Result>(
                    "Results",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Results_Filter);
            private static bool __Results_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Results_CanInsert(ref result);
                return result;
            }
            private static bool __Results_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Results_CanUpdate(ref result);
                return result;
            }
            private static bool __Results_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Results_CanDelete(ref result);
                return result;
            }
            private static bool __Results_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Results_CanRead(ref result);
                return result;
            }
            private static void __Results_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Result e)
            {
                d.Results_Inserting(e);
            }
            private static void __Results_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Result e)
            {
                d.Results_Inserted(e);
            }
            private static void __Results_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Result e)
            {
                d.Results_Updating(e);
            }
            private static void __Results_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Result e)
            {
                d.Results_Updated(e);
            }
            private static void __Results_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Result e)
            {
                d.Results_Deleting(e);
            }
            private static void __Results_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Result e)
            {
                d.Results_Deleted(e);
            }
            private static void __Results_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Result e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Results_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Result, bool>> __Results_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.Result, bool>> filter = null;
                d.Results_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.StudyDesign>
                __StudyDesignsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.StudyDesign>(
                    "StudyDesigns",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyDesigns_Filter);
            private static bool __StudyDesigns_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StudyDesigns_CanInsert(ref result);
                return result;
            }
            private static bool __StudyDesigns_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StudyDesigns_CanUpdate(ref result);
                return result;
            }
            private static bool __StudyDesigns_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StudyDesigns_CanDelete(ref result);
                return result;
            }
            private static bool __StudyDesigns_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StudyDesigns_CanRead(ref result);
                return result;
            }
            private static void __StudyDesigns_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyDesign e)
            {
                d.StudyDesigns_Inserting(e);
            }
            private static void __StudyDesigns_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyDesign e)
            {
                d.StudyDesigns_Inserted(e);
            }
            private static void __StudyDesigns_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyDesign e)
            {
                d.StudyDesigns_Updating(e);
            }
            private static void __StudyDesigns_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyDesign e)
            {
                d.StudyDesigns_Updated(e);
            }
            private static void __StudyDesigns_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyDesign e)
            {
                d.StudyDesigns_Deleting(e);
            }
            private static void __StudyDesigns_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyDesign e)
            {
                d.StudyDesigns_Deleted(e);
            }
            private static void __StudyDesigns_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyDesign e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.StudyDesigns_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StudyDesign, bool>> __StudyDesigns_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StudyDesign, bool>> filter = null;
                d.StudyDesigns_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.StudyTarget>
                __StudyTargetsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.StudyTarget>(
                    "StudyTargets",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StudyTargets_Filter);
            private static bool __StudyTargets_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StudyTargets_CanInsert(ref result);
                return result;
            }
            private static bool __StudyTargets_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StudyTargets_CanUpdate(ref result);
                return result;
            }
            private static bool __StudyTargets_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StudyTargets_CanDelete(ref result);
                return result;
            }
            private static bool __StudyTargets_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StudyTargets_CanRead(ref result);
                return result;
            }
            private static void __StudyTargets_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyTarget e)
            {
                d.StudyTargets_Inserting(e);
            }
            private static void __StudyTargets_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyTarget e)
            {
                d.StudyTargets_Inserted(e);
            }
            private static void __StudyTargets_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyTarget e)
            {
                d.StudyTargets_Updating(e);
            }
            private static void __StudyTargets_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyTarget e)
            {
                d.StudyTargets_Updated(e);
            }
            private static void __StudyTargets_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyTarget e)
            {
                d.StudyTargets_Deleting(e);
            }
            private static void __StudyTargets_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyTarget e)
            {
                d.StudyTargets_Deleted(e);
            }
            private static void __StudyTargets_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StudyTarget e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.StudyTargets_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StudyTarget, bool>> __StudyTargets_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StudyTarget, bool>> filter = null;
                d.StudyTargets_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.TargetType>
                __TargetTypesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.TargetType>(
                    "TargetTypes",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__TargetTypes_Filter);
            private static bool __TargetTypes_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.TargetTypes_CanInsert(ref result);
                return result;
            }
            private static bool __TargetTypes_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.TargetTypes_CanUpdate(ref result);
                return result;
            }
            private static bool __TargetTypes_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.TargetTypes_CanDelete(ref result);
                return result;
            }
            private static bool __TargetTypes_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.TargetTypes_CanRead(ref result);
                return result;
            }
            private static void __TargetTypes_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.TargetType e)
            {
                d.TargetTypes_Inserting(e);
            }
            private static void __TargetTypes_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.TargetType e)
            {
                d.TargetTypes_Inserted(e);
            }
            private static void __TargetTypes_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.TargetType e)
            {
                d.TargetTypes_Updating(e);
            }
            private static void __TargetTypes_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.TargetType e)
            {
                d.TargetTypes_Updated(e);
            }
            private static void __TargetTypes_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.TargetType e)
            {
                d.TargetTypes_Deleting(e);
            }
            private static void __TargetTypes_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.TargetType e)
            {
                d.TargetTypes_Deleted(e);
            }
            private static void __TargetTypes_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.TargetType e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.TargetTypes_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.TargetType, bool>> __TargetTypes_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.TargetType, bool>> filter = null;
                d.TargetTypes_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ApplicationData_InitializingConnection);
            private static void __ApplicationData_InitializingConnection(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.ApplicationData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    #endregion
}
