

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class Article : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Article entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Article()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Article(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Article> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Article.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Article_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Article_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Article.DetailsClass.SetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PMID
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.PMID);
            }
            set
            {
                global::LightSwitchApplication.Article.DetailsClass.SetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.PMID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PMID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PMID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PMID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.Article.DetailsClass.SetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SampleSize
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.SampleSize);
            }
            set
            {
                global::LightSwitchApplication.Article.DetailsClass.SetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.SampleSize, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SampleSize_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SampleSize_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SampleSize_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo CreatedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.CreatedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();
        public global::Microsoft.LightSwitch.Framework.Server.PersonInfo ModifiedByInfo
        {
            get
            {
                global::Microsoft.LightSwitch.Server.IPersonInfoFactory personInfoFactory = global::LightSwitchApplication.Application.Current.GetPersonInfoFactory();
                return (global::Microsoft.LightSwitch.Framework.Server.PersonInfo) personInfoFactory.ResolvePerson(this.ModifiedBy);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Article.DetailsClass.SetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Result> Results
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Results);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Result> ResultsQuery
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetQuery(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Results);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ArticleType ArticleType
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.ArticleType);
            }
            set
            {
                global::LightSwitchApplication.Article.DetailsClass.SetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.ArticleType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ArticleType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Author> Authors
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetValue(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Authors);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Author> AuthorsQuery
        {
            get
            {
                return global::LightSwitchApplication.Article.DetailsClass.GetQuery(this, global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Authors);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Article,
                global::LightSwitchApplication.Article.DetailsClass,
                global::LightSwitchApplication.Article.DetailsClass.IImplementation,
                global::LightSwitchApplication.Article.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass>.Entry
                __ArticleEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass>.Entry(
                    global::LightSwitchApplication.Article.DetailsClass.__Article_CreateNew,
                    global::LightSwitchApplication.Article.DetailsClass.__Article_Created,
                    global::LightSwitchApplication.Article.DetailsClass.__Article_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Article __Article_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Article> es)
            {
                return new global::LightSwitchApplication.Article(es);
            }
            private static void __Article_Created(global::LightSwitchApplication.Article e)
            {
                e.Article_Created();
            }
            private static bool __Article_AllowSaveWithErrors(global::LightSwitchApplication.Article e)
            {
                bool result = false;
                e.Article_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Article.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string> PMID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.PMID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int> SampleSize
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.SampleSize) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Result> Results
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Results) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Result>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.ArticleType> ArticleType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.ArticleType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.ArticleType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Author> Authors
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Authors) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Author>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string PMID { get; set; }
                new string Title { get; set; }
                new int SampleSize { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Results { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ArticleType { get; set; }
                new global::System.Collections.IEnumerable Authors { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Entry
                    PMID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Entry(
                        "PMID",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._PMID_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._PMID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._PMID_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._PMID_GetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._PMID_SetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._PMID_OnValueChanged);
                private static void _PMID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._PMID, sf);
                }
                private static bool _PMID_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.PMID_IsReadOnly(ref result);
                    return result;
                }
                private static void _PMID_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PMID_Validate(r);
                }
                private static string _PMID_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.PMID;
                }
                private static void _PMID_SetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PMID = v;
                }
                private static void _PMID_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.PMID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>.Entry
                    SampleSize = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>.Entry(
                        "SampleSize",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._SampleSize_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._SampleSize_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._SampleSize_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._SampleSize_GetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._SampleSize_SetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._SampleSize_OnValueChanged);
                private static void _SampleSize_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._SampleSize, sf);
                }
                private static bool _SampleSize_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.SampleSize_IsReadOnly(ref result);
                    return result;
                }
                private static void _SampleSize_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SampleSize_Validate(r);
                }
                private static int _SampleSize_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.SampleSize;
                }
                private static void _SampleSize_SetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d, int v)
                {
                    d.ImplementationEntity.SampleSize = v;
                }
                private static void _SampleSize_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.SampleSize_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Result>.Entry
                    Results = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Result>.Entry(
                        "Results",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Results_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Results_GetReferencedEntities,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Results_GetEntityCollection);
                private static void _Results_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Result>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._Results, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Result> _Results_GetReferencedEntities(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass>(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Results, ref d._Results);
                }
                private static global::System.Collections.IEnumerable _Results_GetEntityCollection(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.Results;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.ArticleType>.Entry
                    ArticleType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.ArticleType>.Entry(
                        "ArticleType",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ArticleType_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ArticleType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ArticleType_Validate,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ArticleType_GetCoreImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ArticleType_GetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ArticleType_SetImplementationValue,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ArticleType_Refresh,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._ArticleType_OnValueChanged);
                private static void _ArticleType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.ArticleType>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._ArticleType, sf);
                }
                private static bool _ArticleType_ComputeIsReadOnly(global::LightSwitchApplication.Article e)
                {
                    bool result = false;
                    e.ArticleType_IsReadOnly(ref result);
                    return result;
                }
                private static void _ArticleType_Validate(global::LightSwitchApplication.Article e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ArticleType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ArticleType_GetCoreImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.ArticleType;
                }
                private static global::LightSwitchApplication.ArticleType _ArticleType_GetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ArticleType, global::LightSwitchApplication.ArticleType.DetailsClass>(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.ArticleType, ref d._ArticleType);
                }
                private static void _ArticleType_SetImplementationValue(global::LightSwitchApplication.Article.DetailsClass d, global::LightSwitchApplication.ArticleType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.ArticleType, ref d._ArticleType, (i, ev) => i.ArticleType = ev, v);
                }
                private static void _ArticleType_Refresh(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.ArticleType, ref d._ArticleType);
                }
                private static void _ArticleType_OnValueChanged(global::LightSwitchApplication.Article e)
                {
                    e.ArticleType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Author>.Entry
                    Authors = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Author>.Entry(
                        "Authors",
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Authors_Stub,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Authors_GetReferencedEntities,
                        global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties._Authors_GetEntityCollection);
                private static void _Authors_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Article.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Author>.Data> c, global::LightSwitchApplication.Article.DetailsClass d, object sf)
                {
                    c(d, ref d._Authors, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Author> _Authors_GetReferencedEntities(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Author, global::LightSwitchApplication.Author.DetailsClass>(global::LightSwitchApplication.Article.DetailsClass.PropertySetProperties.Authors, ref d._Authors);
                }
                private static global::System.Collections.IEnumerable _Authors_GetEntityCollection(global::LightSwitchApplication.Article.DetailsClass d)
                {
                    return d.ImplementationEntity.Authors;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Data _PMID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, int>.Data _SampleSize;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Result>.Data _Results;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.ArticleType>.Data _ArticleType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Article, global::LightSwitchApplication.Article.DetailsClass, global::LightSwitchApplication.Author>.Data _Authors;
            
        }
    
        #endregion
    }
    
    #endregion
}
